Traceback (most recent call last):
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furui/.local/share/uv/python/cpython-3.11.5-macos-aarch64-none/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X = np.load('data.npy')
y = np.load('target.npy')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m X [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata.npy[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m y [38;5;241m=[39m np[38;5;241m.[39mload([38;5;124m'[39m[38;5;124mtarget.npy[39m[38;5;124m'[39m)

File [0;32m~/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py:459[0m, in [0;36mload[0;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[1;32m    457[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    458[0m [38;5;28;01melse[39;00m:
[0;32m--> 459[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mfspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m    460[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    462[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data.npy'

